### ISSUE TITLE
Using unit tests

### ISSUE THREAD

**Issue by peter279k** [DivineOmega/php-summary#2]
As title, I think we need to add the unit test with `PHPUnit` instead of using `test.php` in `src` folder.

Also, we need to use the Travis CI build to do the unit tests work automatically :+1:.

**Comment by Jord-JD** [comment]
Agreed. The summary generation algorithm is deterministic, so this should not be too difficult to implement.

Feel free to open a PR if you're interested in adding these tests.

**Comment by Jord-JD** [comment]
Fixed by #3.
