### ISSUE TITLE
Can I install and Use this Script with out Composer ?

### ISSUE THREAD

**Issue by kezenwa** [DivineOmega/php-summary#4]
Don't use Composer and have no interest in ever using Composer as I love to keep things simple while reducing unnecessary Point of Errors / Bugs / Maintenance.

Kindly let me know if I can use this your script without Composer and probably how to go about it if it isn't as simple as Requiring the file **SummaryTool.php**

Thanks

**Comment by Jord-JD** [comment]
I've never attempted to run the package without Composer, but I think you should just be able to require the `SummaryTool.php` and `SentenceTokenizer.php` files.
